name: star_expiry_check
on: [push]
jobs:
  scan:
    name: star_expiry_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: bboysoulcn/star_expiry_check@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}