name: star_expiry_check
on: [push]
jobs:
  scan:
    name: star_expiry_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bboysoulcn/star_expiry_check@main
        env:
          TOKEN: ${{ secrets.TOKEN }}